pages:
  stage: deploy
  script:
    - mkdir public
    - cp index.html public/
    - cp component.css public/
    - cp investment-criteria.js public/
    - cp -r assets public/
  artifacts:
    paths:
      - public
  only:
    - main
